disabled_rules: # rule identifiers to exclude from running
  - force_cast
  - force_try
  - function_parameter_count
  - empty_parentheses_with_trailing_closure
  - implicit_getter
  - legacy_constructor
  - cyclomatic_complexity
  - nesting
  - file_length
  - type_body_length
  - function_body_length
  - todo
  - unused_optional_binding
  - shorthand_operator
  - unused_closure_parameter
  - vertical_parameter_alignment
  - large_tuple
opt_in_rules: # some rules are only opt-in
  - empty_count
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - Source
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - CarthageTest
  - Pods
  - Xcode
  - Source/Internal/Crypto

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
#force_cast: warning # implicitly
#force_try:
#  severity: warning # explicitly
## rules that have both warning and error levels, can set just the warning level
## implicitly
line_length: 168
## they can set both implicitly with an array
#type_body_length:
#  - 300 # warning
#  - 400 # error
## or they can set both explicitly
#file_length:
#  warning: 500
#  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
#type_name:
#  min_length: 3 # only warning
#  max_length: # warning and error
#    warning: 40
#    error: 50
#  excluded: iPhone # excluded via string
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - to
    - at
    - ok
    - ch
    - GlobalAPIKey
    - cellular_2G
    - cellular_3G
    - cellular_4G
    - no_data_received
    - incorrect_response
    - incorrect_url_format
    - no_connection
    - recommendation_api_deactivated
    - no_account_id_found
    - no_placement_found
reporter: "emoji" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)

