platform :ios, '8.0'
use_frameworks!

target 'Project' do
	pod 'Webtrekk',          :path => '..'
end

target 'Tests' do
	pod 'Webtrekk',          :path => '..'
end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configuration_list.set_setting('ENABLE_TESTABILITY', 'YES')
	end
end
