use_frameworks!

install! 'cocoapods', :share_schemes_for_development_pods => false

pod 'Webtrekk', :path => '..'

abstract_target 'iOS' do
	platform :ios, '8.0'

	target 'Automatic Tracking Example'
	target 'Manual Tracking Example'

	target 'Tests' do
		inherit! :search_paths

		# workaround for https://github.com/CocoaPods/CocoaPods/issues/5562
		pod 'Webtrekk', :path => '..'
	end
end

#abstract_target 'watchOS' do
#	platform :watchos, '2.0'
#
#	target 'WatchKit Extension'
#end
