platform :ios, '8.0'
use_frameworks!

install! 'cocoapods', :share_schemes_for_development_pods => false

target 'Automatic Tracking Example'
target 'Manual Tracking Example'

target 'Tests' do
	# workaround for https://github.com/CocoaPods/CocoaPods/issues/5562
	pod 'Webtrekk', :path => '..'

	inherit! :search_paths
end

pod 'Webtrekk', :path => '..'
